Footer 구현 #12
SOPT-all/35-COLLABORATION-iOS-YES24TICKET pull request #14
Opened 2024-11-18 19:05 UTC by lalaurrel

## 🎫 What is the PR?

홈, 콘서트 카테고리, 상세페이지에서 사용되는 footer 구현했습니다.

## 🎫 Changes

- footer view 짜기
- 폰트 적용하기
- 색상 적용하기

## 🎫 Thoughts

줄마다 간격이 달라서 어떻게 구현할지 고민하다가 스택뷰로 묶어서 처리했습니다.

## 🎫 Screenshot

없음.

## 🎫 To Reviewers

스택뷰가 조금 지저분하진 않은지 봐주세요 ....

## 🎫 Related Issues

- Resolved: #12

2024-11-18 19:26 UTC, SungMinCho-Kor requested changes
고생하셨습니다!

2024-11-18 19:26 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Common/Footer.swift
> +class Footer: UIView {
final 키워드에 대해서 공부해보시고 적용해보세요~

2024-11-18 19:26 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Common/Footer.swift
> +        $0.image = UIImage(named: "Vector34")
`UIImage.`으로 접근할 수 있을 것 같아요.
String 값으로 접근하면 휴먼 에러가 발생할 가능성이 있습니다.

2024-11-18 19:26 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Common/Footer.swift
> +    }
1, 2, 3, 4 보다 의미있는 변수명을 사용하시는 것이 유지보수 측면에 더 좋을 것 같아요~

2024-11-18 19:26 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Common/Footer.swift
> +    private func setupViews() {
setStyle, setUI, setLayout으로 역할을 분리하면 좋을 것 같습니다.

2024-11-18 19:26 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Common/Footer.swift
> +
해당 required init은 언제 호출될까요?

2024-11-18 19:26 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Common/Footer.swift
> +    private func setupViews() {
아래 모든 내용을 forEach 고차함수를 활용해서 리팩토링 해보시면 좋을 것 같습니다.

2024-11-19 06:20 UTC, lalaurrel commented on Yes24Ticket/Yes24Ticket/Presentation/Common/Footer.swift
> +    }
마땅한 이름 골똘히 생각중..

2024-11-19 06:20 UTC, lalaurrel commented on Yes24Ticket/Yes24Ticket/Presentation/Common/Footer.swift
> +    }
이게 제일 어려운걸...........

2024-11-19 16:48 UTC, SungMinCho-Kor requested changes
처음에 컨벤션 맞추기가 가장 어렵습니다 ㅠㅠ 화이팅..

2024-11-19 16:48 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Common/Footer.swift
> +        }
stackView.addArrangedSubview 설정 부분과 addSubview 부분을 따로 분리해서 forEach로 적용시키는 것이 더 깔끔할 것 같아요!

2024-11-19 16:48 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Common/Footer.swift
> +            )
매개변수가 2개 미만인 경우에는 줄내림 없애주세요!
아래 모든 경우에도 적용되는 리뷰입니다!

2024-11-19 16:48 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Common/Footer.swift
> +                            .equalTo(
.으로 연결된 부분도 아직 컨벤션이 정해져있지 않기 때문에 줄내림 하지 않는 것이 좋을 것 같아요!

2024-11-19 16:48 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Common/Footer.swift
> +            topAnchor in
forEach는 공통된 매개변수 하나로만 이루어지면 좋을 것 같습니다.

2024-11-19 16:55 UTC, 0gonge approved these changes

2024-11-19 16:55 UTC, 0gonge commented on Yes24Ticket/Yes24Ticket/Presentation/Common/Footer.swift
> +    }
이 부분에서 (.caption_eb_12) 에 괄호 사이 띄어쓰기가 되어있다가 안되어있다가 하는데, 통일 시켜주면 좋을 것 같아요~!

2024-11-19 16:55 UTC, 0gonge commented on Yes24Ticket/Yes24Ticket/Presentation/Common/Footer.swift
> +            }
위에서부터 UI 잡은걸 보면 - StackView 모음에서 가운데 top만 레이아웃을 잡아준 상태인데, 
라벨이랑 버튼이랑 이미지뷰와 같은 좌우 넓이가 고정되어있다보니, 따로 StackView의 Constraint를 잡아주지 않으면, 화면 밖으로 좌 우로 나가는 일이 일어날 수도 있어요.

2024-11-19 17:54 UTC, SungMinCho-Kor approved these changes
고생하셨습니다!!

2024-11-19 17:54 UTC, merged