콘서트 탭 컨트롤러 구현
SOPT-all/35-COLLABORATION-iOS-YES24TICKET pull request #40
Opened 2024-11-23 14:21 UTC by lalaurrel

## 🎫 What is the PR?
-콘서트 뷰에서 사용되는 탭 컨트롤러를 구현했습니다

## 🎫 Changes
- 탭 구현!

## 🎫 Thoughts
- 탭 컨트롤러가 있는 걸로 알고 있는데 피그마 상에서 다른 탭으로 이동하는 부분은 구현되어 있지 않아서 버튼으로만 구현했습니다 

## 🎫 Screenshot
<img width="735" alt="스크린샷 2024-11-23 오전 3 05 16" src="https://github.com/user-attachments/assets/4ca95705-38ab-447a-8f95-dc0af9924a39">

## 🎫 To Reviewers
솝커톤 파이팅!

## 🎫 Related Issues

- Resolved: #37

2024-11-24 17:05 UTC, SungMinCho-Kor requested changes

2024-11-24 17:05 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCategoryView.swift
> +}
띄워주세요~

2024-11-24 17:05 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCategoryView.swift
> +        setupLayout()
setUI, setLayout

2024-11-24 17:05 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCategoryView.swift
> +        addSubview(tabNavigationBar)
forEach

2024-11-24 17:05 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCategoryViewController.swift
> +
컨벤션에 맞춰주세요~

2024-11-24 17:05 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCategoryViewController.swift
> +        let concertCategoryView = ConcertCategoryView()
클래스에 선언하지 않고 viewDidLoad에서 선언해주신 이유가 궁금해요~

2024-11-24 17:05 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/TabBar/CategoryTapNavigationBar.swift
> +        listButton.addBorders(edges: [.top, .bottom, .left], color: .gray200, width: 1)
Border는 layer라서 layoutSublayers일 수도 있어요!
확인해보세요 ㅎ

그리고 줄내림 해주세요~

2024-11-24 17:05 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/TabBar/CategoryTapNavigationBar.swift
> +        setupLayout()
함수 네이밍!

2024-11-24 17:07 UTC, 0gonge reviewed
조금만 더 수정하고 머지 합시다
바쁜데 넘넘 쉬지않고 해준거 칭찬합니다 ~~ 🫶

2024-11-24 17:07 UTC, 0gonge commented on Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCategoryView.swift
> +import SnapKit
희희 컨벤션!!

2024-11-24 17:07 UTC, 0gonge commented on Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCategoryView.swift
> +    }
addSubviews extension 도입할까요~? 의견 적극 환영

2024-11-24 17:07 UTC, 0gonge commented on Yes24Ticket/Yes24Ticket/Presentation/TabBar/CategoryTapNavigationBar.swift
> +    }
Border 넣은거 너무 잘했다요

2024-11-24 17:07 UTC, 0gonge commented on Yes24Ticket/Yes24Ticket/Presentation/TabBar/CategoryTapNavigationBar.swift
> +    }
합세에서는 이렇게 구현해도 되는데 합세 끝나고 여유 생기면 어떻게 구현해볼 지 생각해 보면 좋을 듯 합니다~! 고생했어요

2024-11-25 15:58 UTC, lalaurrel commented on Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCategoryViewController.swift
> +        let concertCategoryView = ConcertCategoryView()
임시로 화면 띄워보려고 했습니다~! 수정해서 올릴게용

2024-11-25 16:35 UTC, 0gonge commented on Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCategoryView.swift
> +            $0.leading.trailing.equalToSuperview()
이거 다음부턴 horizontalEdges로 쓰면 좋아요~!

2024-11-25 16:35 UTC, 0gonge commented on Yes24Ticket/Yes24Ticket/Presentation/TabBar/CategoryTapNavigationBar.swift
> +        addSubview(listButton)
여기도 ForEach 할 수 있겠다!

2024-11-25 16:36 UTC, SungMinCho-Kor requested changes
다시! 수정! 해주세요!

2024-11-25 16:36 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCategoryView.swift
> +        backgroundColor = .white
setStyle로 함수화해주세요

2024-11-25 16:36 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCategoryView.swift
> +        [closedSearchBarView, customNavBar, tabNavigationBar].forEach {
줄 내림

2024-11-25 16:36 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCategoryViewController.swift
> +        }
setLayout

2024-11-25 16:36 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/TabBar/CategoryTapNavigationBar.swift
> +        addSubview(listButton)
forEach

2024-11-25 16:39 UTC, lalaurrel commented on Yes24Ticket/Yes24Ticket/Presentation/TabBar/CategoryTapNavigationBar.swift
> +        listButton.addBorders(edges: [.top, .bottom, .left], color: .gray200, width: 1)
layoutSublayers로 바꾸니까 에러나길래 보니까 얘는 UIView의 레이아웃과는 무관하다고 합니다요

2024-11-25 16:50 UTC, lalaurrel commented on Yes24Ticket/Yes24Ticket/Presentation/TabBar/CategoryTapNavigationBar.swift
> +        addSubview(listButton)
아니 이거 왜 안떠

2024-11-25 16:51 UTC, SungMinCho-Kor requested changes

2024-11-25 16:51 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCategoryView.swift
> +        ].forEach {
요기 Control(^) + M 한 번 해주세요 ㅎ..ㅎ

2024-11-25 16:51 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/TabBar/CategoryTapNavigationBar.swift
> +        [recommendButton, rankingButton, listButton].forEach(addSubview)
여기도 Control(^) + i 한 번 해주세요~

2024-11-25 16:54 UTC, SungMinCho-Kor approved these changes
고생했어... 내가 미안 ㅎ

2024-11-25 16:55 UTC, merged