콘서트 카테고리 뷰 구현
SOPT-all/35-COLLABORATION-iOS-YES24TICKET pull request #45
Opened 2024-11-26 18:17 UTC by lalaurrel

## 🎫 What is the PR?
- 셀만들고 콘서트 뷰에서 컴포지셔널 레이아웃으로 구현했습니다

## 🎫 Changes
- 셀
- 뷰 구현

## 🎫 Thoughts
- 피그마 상 여백이 셀 가로 여백이 11로 설정되어 있어서 수정해보면 피그마보다 간격이 커보이고 조정을 해도 변화가 없어서 계속 수정하다가 도움을 요청하고자 올립니다
- 참고로 사이 간격을 11로 설정하면 양벽에 여백이 너무 커져서.. 피그마 잘못인지 제가 잘못 설정하고 있는건지 모르겠습니다 헬프미

## 🎫 Screenshot
![Simulator Screen Recording - iPhone 16 Pro - 2024-11-27 at 03 17 12](https://github.com/user-attachments/assets/a5731497-8ca2-4833-9c3c-418697c611cb)

## 🎫 To Reviewers
- 간격 설정 뭐가 잘못된건가요,,
- 
## 🎫 Related Issues

- Resolved: #35

2024-11-26 18:24 UTC, SungMinCho-Kor requested changes
고생하셨습니다!...

2024-11-26 18:24 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCategoryView.swift
> +            section.contentInsets = NSDirectionalEdgeInsets(top: 10, leading: 0, bottom: 10, trailing: 0)
control m

2024-11-26 18:24 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCategoryView.swift
> +    private lazy var collectionView: UICollectionView = {
then을 사용해주세요~

2024-11-26 18:24 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCategoryView.swift
> +    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
control + m

2024-11-26 18:24 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCategoryView.swift
> +        cell.dateLabel.text = "2024. 12. 07 - 12. 08"
1. Cell의 요소에 직접 접근하는 것이 아니라 Cell의 프로퍼티는 private로 감싸고 configure 함수를 통해서 데이터를 전달해보세요~

2. 더미 데이터는 모델로 묶어서 mockData를 만들어서 주입해주세요~

2024-11-26 18:24 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCategoryView.swift
> +    }
사용하지 않는 함수는 삭제해주세요~

2024-11-26 18:24 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCollectionViewCell.swift
> +class ConcertCollectionViewCell: UICollectionViewCell {
final

2024-11-26 18:24 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCollectionViewCell.swift
> +    static let reuseIdentifier = "ConcertCollectionViewCell"
한 줄 띄기

2024-11-26 18:24 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCollectionViewCell.swift
> +    }()
1. private 넣어주세요
2. then 사용해주세요

2024-11-26 18:24 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCollectionViewCell.swift
> +    }
setUI, setLayout으로 함수화하면 좋을 것 같아요~

2024-11-26 19:12 UTC, SungMinCho-Kor requested changes

2024-11-26 19:12 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCategoryView.swift
> +}
extension의 처음과 끝은 띄워주세요~

2024-11-26 19:12 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCollectionViewCell.swift
> +        [bigImageView, titleLabel, subtitleLabel, dateLabel].forEach {
control m!

2024-11-26 19:12 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCollectionViewCell.swift
> +    func configure(image: UIImage?, title: String, subtitle: String, date: String) {
control m!
그리고 model로 묶으면 좋을 것 같아요~

2024-11-26 19:12 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertModel.swift
> +}
처음과 끝을 띄워주세요~

2024-11-26 19:12 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertModel.swift
> +    static let concerts: [Concert] = [
여기드요~

2024-11-28 07:08 UTC, SungMinCho-Kor approved these changes

2024-11-28 07:08 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertCollectionViewCell.swift
> +}
한 줄 띄워주세요~

2024-11-28 18:01 UTC, 0gonge approved these changes
늦게 봐서 미안합니다~! 
너무너무 고생했어요 잘한다잘한다

2024-11-28 18:01 UTC, 0gonge commented on Yes24Ticket/Yes24Ticket/Presentation/Concert/ConcertModel.swift
> +import UIKit
정말 간단한거지만.. 남겨요 space

2024-11-28 18:18 UTC, merged