알립니다 구현
SOPT-all/35-COLLABORATION-iOS-YES24TICKET pull request #46
Opened 2024-11-27 00:54 UTC by 0gonge

## 🎫 What is the PR?

알립니다 TicketDetailView의 전반적인 작업을 완료했습니다!

## 🎫 Changes

- 알립니다 셀 Expanded 구현
- 펼쳐졌을 때 border 점선 구현
- 예매하기 버튼 구현
- Footer TableView에 구현
- ExpandedView 구현

## 🎫 Thoughts

Expanded를 어떻게 하면 구현할 수 있을 지 공부해볼 수 있는 좋은 시간이었습니다. 
TableView에 대해서 한 층 더 깊이 알아볼 수 있었던 시간..
Expanded에 더불어 재사용 셀들과 다른 하나의 셀의 화살표 동작, 펼쳐졌을 때 섹션에 점선 뷰가 나타나야 함... 등등 까다로운 부분이 많았습니다. 
이를 구현하기 위해서는 테이블 뷰를 구현하기 위해 써주는 각각의 메서드들이 어떤 역할을 하는지 잘 알아야 했고, 그에 따라 조건을 걸어주어 맞는 동작을 하게 하는 것이 무엇보다도 중요했습니다. 그리고 각각의 화면에 그려지는 View, layer의 차이도 조금 더 명확히 알 수 있었던 시간이었습니다. 
그러니, 저의 코드에서 TableView에서 조건을 걸어준 부분을 조금 유심하게 봐 주셨으면 좋겠습니다. 
그리고 Footer를 TableViewHeaderFooterView로 붙여주기 위한 snp도 공부할 수 있었습니다. 

## 🎫 Screenshot

https://github.com/user-attachments/assets/64438e26-28d0-49e5-9306-3a1cd15d417a

## 🎫 To Reviewers

TableView 구현 조건 위주로 봐주세요! 

## 🎫 Related Issues

- Resolved: #38

진짜 까다로웠다... 드디어 하나 끝냈따...

2024-11-27 16:34 UTC, lalaurrel approved these changes
대박대박 !!!!!!! 고생하셨습니다 여경팀장님이 나라다.

2024-11-27 16:34 UTC, lalaurrel commented on Yes24Ticket/Yes24Ticket/Application/SceneDelegate.swift
> +            rootViewController: TicketDetailController()
혹쉬 이거 탭바로 다시 안바꿔두 돼?! 🤓

2024-11-27 16:34 UTC, lalaurrel commented on Yes24Ticket/Yes24Ticket/Presentation/DetailPage/View/TableViewFooter.swift
> +    private let footer = Footer()
푸터다 ㅎㅎ

2024-11-27 18:06 UTC, 0gonge commented on Yes24Ticket/Yes24Ticket/Application/SceneDelegate.swift
> +            rootViewController: TicketDetailController()
다시 바꿔야 해 ㅋㅋㅋ 다음 타자가 바꿔줄거라고 믿고있어...

2024-11-28 07:13 UTC, SungMinCho-Kor requested changes
어려운 부분을 잘 해내셨네요!! 화이팅화이팅

2024-11-28 07:13 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/Common/Footer.swift
> +////
주석은 삭제해도 될 것 같아요!

2024-11-28 07:13 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Model/InfoConfiguration.swift
> +    ]
여기도 Control m 해주시면 좋을 것 같아요!

2024-11-28 07:13 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/DetailPage/View/DetailTableViewCell.swift
> +class DetailTableViewCell: UITableViewCell {
fina 붙여주세요!

2024-11-28 07:13 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/DetailPage/View/DetailTableViewCell.swift
> +    static let identifier: String = "DetailTableViewCell"
UITableViewCell의 identifier도 UICollectionViewCell처럼 extension으로 구현하면 어떨까요?

2024-11-28 07:13 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/DetailPage/View/ExpandedView.swift
> +    private let firstLabel = UILabel().then {
한 칸 띄워주세요~

2024-11-28 07:13 UTC, SungMinCho-Kor commented on Yes24Ticket/Yes24Ticket/Presentation/DetailPage/ViewController/TicketDetailController.swift
> +            .forEach(view.addSubview)
줄내림과 띄어쓰기 컨벤션 확인해주세요!

2024-11-28 12:17 UTC, 0gonge commented on Yes24Ticket/Yes24Ticket/Presentation/Common/Footer.swift
> +////
감사합니다 : )

2024-11-28 12:18 UTC, 0gonge commented on Yes24Ticket/Yes24Ticket/Model/InfoConfiguration.swift
> +    ]
반영완료했습니다 감사합니다!

2024-11-28 12:18 UTC, 0gonge commented on Yes24Ticket/Yes24Ticket/Presentation/DetailPage/View/DetailTableViewCell.swift
> +class DetailTableViewCell: UITableViewCell {
앗 그걸 놓쳤네요 감사합니다!

2024-11-28 12:38 UTC, 0gonge commented on Yes24Ticket/Yes24Ticket/Presentation/DetailPage/ViewController/TicketDetailController.swift
> +            .forEach(view.addSubview)
확인했습니다!

2024-11-28 12:38 UTC, 0gonge commented on Yes24Ticket/Yes24Ticket/Presentation/DetailPage/View/ExpandedView.swift
> +    private let firstLabel = UILabel().then {
넹~

2024-11-28 12:38 UTC, 0gonge commented on Yes24Ticket/Yes24Ticket/Presentation/DetailPage/View/DetailTableViewCell.swift
> +    static let identifier: String = "DetailTableViewCell"
반영완료 했습니다!

2024-11-28 13:15 UTC, SungMinCho-Kor approved these changes
드디어! 성공!

2024-11-28 13:15 UTC, merged